export const EN_PAGES = [
  '/en/',
  '/en/projects/',
  '/en/about/',
  '/en/turnaround/',
  '/en/builder/',
  '/en/consulting/',
  '/en/contact/',
  '/en/writing/',
  '/en/talks/',
  '/en/publications/',
  '/en/privacy/',
  '/en/imprint/',
  '/en/case-studies/jaden-data-company-building/',
  '/en/case-studies/kfw-genai-portfolio/',
  '/en/case-studies/bosch-procurement-ai/',
  '/en/case-studies/apg-pension-assistant/',
];

export const ALL_PAGES = [
  ...EN_PAGES,
  '/pl/',
  '/pl/turnaround/',
  '/pl/builder/',
  '/pl/about/',
  '/de/',
  '/de/turnaround/',
  '/de/builder/',
  '/de/about/',
];
